sudo: required
services:
  - docker

before_install: 
  - docker build -t del/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true del/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: $AWS_REGION
  app: frontend
  env: frontend-env
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: docker
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
